package it.unirc.pistony.pojo.Prenota;
// Generated 17 dic 2020, 16:53:34 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;
import it.unirc.pistony.pojo.Intervento.*;

import it.unirc.pistony.pojo.Cliente.Cliente;

/**
 * Prenota generated by hbm2java
 */
public class Prenota implements java.io.Serializable {

	private int idprenota;
	private Cliente cliente;
	private String descrizione;
	private Set<Intervento> interventi = new HashSet<Intervento>(0);

	public Prenota() {
	}









	public Prenota(Cliente cliente, String descrizione) {
		super();
		this.cliente = cliente;
		this.descrizione = descrizione;
	}









	public Prenota(int idprenota) {
		this.idprenota = idprenota;
	}

	public int getIdprenota() {
		return idprenota;
	}

	public void setIdprenota(int idprenota) {
		this.idprenota = idprenota;
	}

	public Cliente getCliente() {
		return cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Intervento> getInterventi() {
		return interventi;
	}

	public void setInterventi(Set<Intervento> interventi) {
		this.interventi = interventi;
	}


}
