package it.unirc.pistony.pojo.Acquisto;
// Generated 17 dic 2020, 16:53:34 by Hibernate Tools 5.4.21.Final

import java.util.Date;

import it.unirc.pistony.pojo.Cliente.Cliente;
import it.unirc.pistony.pojo.Componente.Componente;

/**
 * Acquisto generated by hbm2java
 */
public class Acquisto implements java.io.Serializable {

	private AcquistoId id;
	private Date data;
	private Integer quantAcquistata;
	
	

	public Acquisto() {
	}


	
	public Acquisto(AcquistoId id, Date data, Integer quantAcquistata) {
		super();
		this.id = id;
		this.data = data;
		this.quantAcquistata = quantAcquistata;
	}



	public AcquistoId getId() {
		return this.id;
	}

	public void setId(AcquistoId id) {
		this.id = id;
	}



	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Integer getQuantAcquistata() {
		return this.quantAcquistata;
	}

	public void setQuantAcquistata(Integer quantAcquistata) {
		this.quantAcquistata = quantAcquistata;
	}

}
