package it.unirc.pistony.pojo.Acquisto;
// Generated 17 dic 2020, 16:53:34 by Hibernate Tools 5.4.21.Final

/**
 * AcquistoId generated by hbm2java
 */
public class AcquistoId implements java.io.Serializable {

	private int idacquisto;
	private int idcliente;
	private int idcomponente;

	public AcquistoId() {
	}



	public AcquistoId(int idacquisto, int idcliente, int idcomponente) {
		super();
		this.idacquisto = idacquisto;
		this.idcliente = idcliente;
		this.idcomponente = idcomponente;
	}



	public int getIdacquisto() {
		return this.idacquisto;
	}

	public void setIdacquisto(int idacquisto) {
		this.idacquisto = idacquisto;
	}


	

	public int getIdcomponente() {
		return idcomponente;
	}

	public void setIdcomponente(int idcomponente) {
		this.idcomponente = idcomponente;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcquistoId))
			return false;
		AcquistoId castOther = (AcquistoId) other;

		return (this.getIdacquisto() == castOther.getIdacquisto())
				&& (this.getIdcliente() == castOther.getIdcliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdacquisto();
		result = 37 * result + this.getIdcliente();
		return result;
	}

}
