package it.unirc.pistony.pojo.Accountcliente;
// Generated 17 dic 2020, 16:53:34 by Hibernate Tools 5.4.21.Final

import it.unirc.pistony.pojo.Cliente.Cliente;

/**
 * Accountcliente generated by hbm2java
 */
public class Accountcliente implements java.io.Serializable {

	private int idcliente;
	private Cliente cliente;
	private String email;
	private String password;



	public Accountcliente() {
		super();
	}

	public Accountcliente(String email, String password) {
		super();
		this.email = email;
		this.password = password;
	}

	public int getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(int idcliente) {
		this.idcliente = idcliente;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
