package it.unirc.pistony.pojo.Accounttitolare;

import it.unirc.pistony.pojo.titolare.Titolare;

// Generated 17 dic 2020, 16:46:31 by Hibernate Tools 5.4.21.Final

/**
 * Accounttitolare generated by hbm2java
 */
public class Accounttitolare implements java.io.Serializable {

	private int idtitolare;
	
	private String email;
	private String password;
	private Titolare titolare;

	public Accounttitolare() {
	}

	public Accounttitolare(Titolare titolare) {
		this.titolare = titolare;
	}

	public Accounttitolare(Titolare titolare, String email, String password) {
		this.titolare = titolare;
		this.email = email;
		this.password = password;
	}
	
	

	public Accounttitolare(String email, String password) {
		super();
		this.email = email;
		this.password = password;
	}

	public int getIdtitolare() {
		return this.idtitolare;
	}

	public void setIdtitolare(int idtitolare) {
		this.idtitolare = idtitolare;
	}

	public Titolare getTitolare() {
		return this.titolare;
	}

	public void setTitolare(Titolare titolare) {
		this.titolare = titolare;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
