package it.unirc.pistony.pojo.Cliente;
// Generated 17 dic 2020, 16:53:34 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

import it.unirc.pistony.pojo.Accountcliente.Accountcliente;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer idcliente;
	private String nome;
	private String cognome;
	private String cfPiva;
	private Indirizzo indirizzo;
	private String telefono;
	private Accountcliente accountcliente;
	

	public Cliente() {
	}

	public Cliente(Integer idcliente, String nome, String cognome, String cfPiva, Indirizzo indirizzo,
			String telefono) {
		super();
		this.idcliente = idcliente;
		this.nome = nome;
		this.cognome = cognome;
		this.cfPiva = cfPiva;
		this.indirizzo = indirizzo;
		this.telefono = telefono;
	}



	public Integer getIdcliente() {
		return idcliente;
	}


	public void setIdcliente(Integer idcliente) {
		this.idcliente = idcliente;
	}


	public String getNome() {
		return nome;
	}


	public void setNome(String nome) {
		this.nome = nome;
	}


	public String getCognome() {
		return cognome;
	}


	public void setCognome(String cognome) {
		this.cognome = cognome;
	}


	public String getCfPiva() {
		return cfPiva;
	}


	public void setCfPiva(String cfPiva) {
		this.cfPiva = cfPiva;
	}


	public Indirizzo getIndirizzo() {
		return indirizzo;
	}


	public void setIndirizzo(Indirizzo indirizzo) {
		this.indirizzo = indirizzo;
	}


	public String getTelefono() {
		return telefono;
	}


	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}


	public Accountcliente getAccountcliente() {
		return accountcliente;
	}


	public void setAccountcliente(Accountcliente accountcliente) {
		this.accountcliente = accountcliente;
	}




}
