package it.unirc.pistony.pojo.Intervento;
// Generated 17 dic 2020, 16:53:34 by Hibernate Tools 5.4.21.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import it.unirc.pistony.pojo.Meccanico.Meccanico;
import it.unirc.pistony.pojo.Prenota.Prenota;

/**
 * Intervento generated by hbm2java
 */
public class Intervento implements java.io.Serializable {

	private Integer idintervento;
	private Prenota prenota;
	private String tipo;
	private double prezzo;
	private Date dataIntervento;
	private Set<Meccanico> meccanici;

	public Intervento() {
	}



	public Intervento(Integer idintervento, Prenota prenota, String tipo, double prezzo, Date dataIntervento,
			Set<Meccanico> meccanici) {
		super();
		this.idintervento = idintervento;
		this.prenota = prenota;
		this.tipo = tipo;
		this.prezzo = prezzo;
		this.dataIntervento = dataIntervento;
		this.meccanici = meccanici;
	}









	public Integer getIdintervento() {
		return this.idintervento;
	}

	public void setIdintervento(Integer idintervento) {
		this.idintervento = idintervento;
	}

	public Prenota getPrenota() {
		return this.prenota;
	}

	public void setPrenota(Prenota prenota) {
		this.prenota = prenota;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}


	public double getPrezzo() {
		return prezzo;
	}

	public void setPrezzo(double prezzo) {
		this.prezzo = prezzo;
	}

	public Date getDataIntervento() {
		return this.dataIntervento;
	}

	public void setDataIntervento(Date dataIntervento) {
		this.dataIntervento = dataIntervento;
	}

	public Set<Meccanico> getMeccanici() {
		return meccanici;
	}

	public void setMeccanici(Set<Meccanico> meccanici) {
		this.meccanici = meccanici;
	}



}
