package it.unirc.pistony.pojo.Meccanico;
// Generated 17 dic 2020, 16:53:34 by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import it.unirc.pistony.pojo.Intervento.Intervento;



/**
 * Meccanico generated by hbm2java
 */
public class Meccanico implements java.io.Serializable {

	private Integer idmeccanico;
	private String nome;
	private String cognome;
	private String indirizzo;
	private String settore;
	private Date dataAssunzione;
	private String tipoContratto;
	private Set<Intervento> interventi;

	public Meccanico() {
	}

	public Meccanico(String nome, String cognome, String indirizzo, String settore, Date dataAssunzione,
			String tipoContratto) {
		this.nome = nome;
		this.cognome = cognome;
		this.indirizzo = indirizzo;
		this.settore = settore;
		this.dataAssunzione = dataAssunzione;
		this.tipoContratto = tipoContratto;
	}

	public Integer getIdmeccanico() {
		return this.idmeccanico;
	}

	public void setIdmeccanico(Integer idmeccanico) {
		this.idmeccanico = idmeccanico;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getSettore() {
		return this.settore;
	}

	public void setSettore(String settore) {
		this.settore = settore;
	}

	public Date getDataAssunzione() {
		return this.dataAssunzione;
	}

	public void setDataAssunzione(Date dataAssunzione) {
		this.dataAssunzione = dataAssunzione;
	}

	public String getTipoContratto() {
		return this.tipoContratto;
	}

	public void setTipoContratto(String tipoContratto) {
		this.tipoContratto = tipoContratto;
	}


	public Set<Intervento> getInterventi() {
		return interventi;
	}

	public void setInterventi(Set<Intervento> interventi) {
		this.interventi = interventi;
	}
	

}
